import { ArrowLeft, ArrowRight, ArrowUpRight } from 'lucide-react';
import Nav from '@/components/sections/Nav';
import Footer from '@/components/sections/Footer';
import PageMeta from '@/components/seo/page-meta';
import { projects, projectPath, type PortfolioProject } from '@/data/projects';
export default function ProjectCaseStudy({ project }: { project: PortfolioProject }) {
  const next = projects[(projects.indexOf(project) + 1) % projects.length];
  return <div className="min-h-screen bg-[#0a0b10] text-white">
    <PageMeta title={`${project.name} Website Case Study | Vertex Digital`} description={project.description} canonicalPath={projectPath(project)} /><Nav />
    <main className="pt-28 md:pt-36">
      <header className="page-gutter pb-12 pt-8 md:pb-16"><a href="/work" className="inline-flex items-center gap-2 text-sm text-[#aab3c4] hover:text-white"><ArrowLeft size={16} />All work</a><p className="mt-10 text-xs font-medium uppercase tracking-[.2em] text-[#a99bff]">{project.category} / Website case study</p><h1 className="mt-5 font-display text-4xl font-semibold leading-tight tracking-[-.045em] sm:text-5xl md:text-7xl">{project.name}</h1><div className="mt-6 flex flex-col justify-between gap-7 lg:flex-row lg:items-end"><p className="max-w-2xl text-xl leading-8 text-[#bac2d0] md:text-2xl md:leading-9">{project.headline}</p><a href={project.url} target="_blank" rel="noopener noreferrer" className="inline-flex w-fit shrink-0 items-center gap-3 rounded-full bg-[#765EFF] px-6 py-3.5 text-sm font-semibold hover:bg-[#8b77ff]">View live website <ArrowUpRight size={18} /></a></div></header>
      <div className="page-gutter">
        <figure className="overflow-hidden rounded-2xl p-3 sm:p-8 md:p-12" style={{ background: project.color }}><img src={project.image} alt={`${project.name} desktop homepage screenshot`} width={1265} height={713} className="w-full rounded-lg shadow-2xl" fetchPriority="high" /></figure>
        <dl className="grid gap-7 border-b border-white/10 py-9 sm:grid-cols-3"><div><dt className="text-xs uppercase tracking-[.16em] text-[#929cad]">Project</dt><dd className="mt-3 text-sm leading-7">Independent portfolio build</dd></div><div><dt className="text-xs uppercase tracking-[.16em] text-[#929cad]">Market</dt><dd className="mt-3 text-sm leading-7">{project.location}</dd></div><div><dt className="text-xs uppercase tracking-[.16em] text-[#929cad]">Our scope</dt><dd className="mt-3 text-sm leading-7">{project.scope.join(' · ')}</dd></div></dl>
        <section className="grid gap-8 py-16 md:grid-cols-[.65fr_1fr] md:py-24"><div><p className="text-xs uppercase tracking-[.2em] text-[#a99bff]">01 / The brief</p><h2 className="mt-4 font-display text-3xl font-semibold md:text-4xl">Clarity starts with<br />the right questions.</h2></div><div className="space-y-8"><div><h3 className="text-lg font-medium">The challenge</h3><p className="mt-3 text-base leading-8 text-[#aab3c4]">{project.challenge}</p></div><div><h3 className="text-lg font-medium">Our approach</h3><p className="mt-3 text-base leading-8 text-[#aab3c4]">{project.approach}</p></div></div></section>
        <section className="border-t border-white/10 py-14 md:py-20"><p className="text-xs uppercase tracking-[.2em] text-[#a99bff]">02 / Design decisions</p><h2 className="mt-4 font-display text-3xl font-semibold md:text-4xl">The thinking behind the screens.</h2><div className="mt-10 grid gap-8 md:grid-cols-3">{project.decisions.map((decision, i) => <div key={decision.title} className="border-t border-white/15 pt-6"><span className="text-sm text-[#a99bff]">0{i + 1}</span><h3 className="mt-5 text-xl font-medium leading-7">{decision.title}</h3><p className="mt-4 text-sm leading-7 text-[#aab3c4]">{decision.text}</p></div>)}</div></section>
        <section className="grid items-center gap-10 rounded-2xl border border-white/10 bg-[#11131b] p-5 sm:p-8 lg:grid-cols-[1fr_.32fr] lg:p-12" aria-label="Desktop and mobile website screenshots"><figure><img src={project.detail} alt={`${project.name} service or project section screenshot`} width={1265} height={713} loading="lazy" className="w-full rounded-lg border border-white/10" /><figcaption className="mt-5 max-w-2xl text-sm leading-6 text-[#aab3c4]">{project.detailCaption}</figcaption></figure><figure className="mx-auto w-full max-w-[250px]"><img src={project.mobile} alt={`${project.name} mobile homepage at 390 pixels wide`} width={390} height={844} loading="lazy" className="w-full rounded-[1.8rem] border-[6px] border-[#2a2d38]" /><figcaption className="mt-4 text-center text-xs text-[#aab3c4]">The same experience, on a smaller screen.</figcaption></figure></section>
        <section className="grid gap-8 py-16 md:grid-cols-[.65fr_1fr] md:py-24"><div><p className="text-xs uppercase tracking-[.2em] text-[#a99bff]">03 / The finished experience</p><h2 className="mt-4 font-display text-3xl font-semibold md:text-4xl">Built. Deployed.<br />Ready to explore.</h2></div><div><p className="text-base leading-8 text-[#aab3c4]">{project.outcome}</p><a href={project.url} target="_blank" rel="noopener noreferrer" className="mt-6 inline-flex items-center gap-2 border-b border-[#a99bff]/50 pb-2 font-medium text-[#c5bcff] hover:text-white">Explore the live website <ArrowUpRight size={17} /></a><p className="mt-8 text-xs leading-6 text-[#8792a4]">Independent design and development work for portfolio presentation. This is not a claim of an official client engagement or endorsement. Screenshots show the linked deployment; business names and source images belong to their respective owners.</p></div></section>
      </div>
      <section className="border-y border-white/10 bg-[#11121a] py-12 md:py-16"><div className="page-gutter flex flex-col justify-between gap-8 sm:flex-row sm:items-center"><div><p className="text-xs uppercase tracking-[.2em] text-[#a99bff]">Next case study</p><a href={projectPath(next)} className="mt-4 inline-flex items-center gap-4 font-display text-2xl font-semibold sm:text-3xl">{next.name}<ArrowRight size={23} /></a></div><a href="/contact" className="inline-flex w-fit items-center gap-2 rounded-full border border-white/20 px-6 py-3 text-sm hover:bg-white/5">Let’s talk about your website <ArrowUpRight size={16} /></a></div></section>
    </main><Footer />
  </div>;
}
